### ISSUE TITLE
Lots of deprecation warnings

### ISSUE THREAD

**Issue by sercero** [OGRECave/ogre-audiovideo#9]
I am compiling against OGRE 1.11.6 and I am getting lots of warnings about deprecated functions:
OGRE_DEPRECATED void bind(T* rep) { shared_ptr<T>::reset(rep); }
OGRE_DEPRECATED bool isNull(void) const { return !shared_ptr<T>::operator bool(); }
OGRE_DEPRECATED void setNull() { shared_ptr<T>::reset(); }

I'm not sure how to fix them myself

**Comment by paroj** [comment]
See https://ogrecave.github.io/ogre/api/latest/deprecated.html

**Comment by sercero** [comment]
@paroj can you make a release of this?

Because I want to solve the deprecation warnings, but let people who perhaps use an earlier version of OGRE to be able to have something to use.

Thanks.

**Comment by paroj** [comment]
done

**Comment by sercero** [comment]
Thanks
